### ISSUE TITLE
Pipe Diameter Unit error

### ISSUE THREAD

**Issue by malcolm-dsider** [NREL/GEOPHIRES-X#92]
There seems to be a problem with pipe diameters, reproducible with Example 1.

Example one says:

Production Well Diameter,7,		     			---[inch]
Injection Well Diameter,7,					---[inch]

But reports them as:

      Injection well casing ID:                               0.005 meter
      Production well casing ID:                              0.005 meter

0.005 is 0.19685039 Inches!

Debugging indicates that this is not just a conversion error in reporting - the value of 0.005 is being passed into the Output object.

It sounds like a double conversion or some confusion about when conversion is need... I will track it down.

**Comment by softwareengineerprogrammer** [comment]
https://github.com/NREL/GEOPHIRES-X/blob/3d5d75477ba93df399f66646d433ff56a8e6bbe5/tests/examples/example1.out#L48-L49

**Comment by malcolm-dsider** [comment]
This issue is fixed in the HIP-RA-X branch and committed. As @kfbeckers pointed out, it was NOT impacting the internal calculations, only the reporting. As suggested by @softwareengineerprogrammer, the bug was in the Parameters object.ConvertUnitsBack function.

The impact of this fix will be somewhat annoying; - some of the unit tests will fail because the "correct" examples are, in fact, not correct but rather have the wrong units due to this bug. A simple update of the "correct" files will fix the unit tests.

**Comment by softwareengineerprogrammer** [comment]
Re-opening because fix is still pending integration into repository, likely to be merged in https://github.com/softwareengineerprogrammer/GEOPHIRES-X/pull/3.

**Comment by softwareengineerprogrammer** [comment]
Looking at this now; the suggested fix does not resolve. Rather, the issue appears to be in special casing logic in WellBores.py: https://github.com/NREL/GEOPHIRES-X/blob/0a84d0c27399dbb5596c7973896119c2e310cc82/src/geophires_x/WellBores.py#L931-L940

(Will continue investigating fix, just wanted to make a note of this)

**Comment by malcolm-dsider** [comment]
The code identified (lines 931-940 in Wellbores.py seems correct. It does get called in the case of Example 1, because Example 1 sets the pipe diameters to 7 inches.  Since 7> 2, the code gets called and converts the units to meters. It also marks these parameters as not having their default units, so the function Parameters.ConvertUnitsBack eventually gets called, and that was what was failing to correctly switch it back to the units that the user asked for.

 

The underlying problem here is that the documentation calls for the pipe diameters to be specified in inches, but the underlying code assumes meters. Hence the need for a hardcoded switch. The alternative is to change the underlying definition and documentation, but I don’t think we want to go there.

**Comment by softwareengineerprogrammer** [comment]
Addressed by https://github.com/NREL/GEOPHIRES-X/pull/99
